@startuml

Class01 "1 one" *-- "0..* many" Class02 : contains >

(Class01,Class02) . Enrollment

Class03 o-- Class04 : promotes
    note on link #red: this is the relation

Class05 --> "1" Class06 : demotes
    note on link : CRUD

Object <|-- ArrayList

Object --|> ArrayList

Object -|> ArrayList

A <|- B
B -|> C
B <|-- D
B --|> E
F <|-- B

@enduml
