    //@Metric "data type" 9

class model Cl_datatype10

enumeration Mode
    during
    before
    after

datatype URL

class Something
    attributes
        int : Integer
        int0 : Integer[0..1]
        real : Real
        real0 : Real[0..1]
        str : String
        str0 : String[0..1]
        bool : Boolean
        bool0 : Boolean[0..1]
        date : Date
        date0 : Date[0..1]
        dt : DateTime
        dt0 : DateTime[0..1]
        time : Time
        time0 : Time[0..1]
        mode : Mode
        mode0 : Mode[0..1]
        url0 : URL[0..1]
        void : NullType