@startuml
Object <|-- ArrayList

class Object [[http://meylan.unblog.fr{optional tip\ntoto<br/>titi<b>kfkf</b>}]]

abstract class Object <<abstract>> {
    Object[] elementData [[[http://meylan.fr{another tip <b>sdjs</b>}]]]
    __
    {method} size() <<abstract>>
    __invariant__
    inv1
    inv2
}


@enduml
