    # speech


class model Cl_main
    | this is the documentation of the class

Le concept de Personne est important.
The concept of Manager is important.

A Manager is a Personne.

L'age d'une personne est un entier.
Le nom d'une personne est une chaine.
La taille d'une personne est un reel.

A Person IsParent of zero or many children of type Person.
Une Personne a entre 0 et 2 parents de type Personne.

A File has zero or one parent of type Directory.
Un Fichier a zero ou un parent de type Repertoire.

Si m est l'un des maisonsVisitees d'une Personne p
    alors p est l'un des visiteurs de m.

Si m est l'un des maisonsVisitees d'une Personne p
    alors p est l'un des visiteurs de la Maison m.
