# coding=utf-8
import modelscript.scripts.demo.all
import modelscript.scripts.accesses.all
import modelscript.scripts.aui.all
import modelscript.scripts.classes.all
import modelscript.scripts.glossaries.all
import modelscript.scripts.megamodels.all
import modelscript.scripts.metamodels.all
import modelscript.scripts.objects.all
import modelscript.scripts.participants.all
import modelscript.scripts.permissions.all
import modelscript.scripts.projects.all
import modelscript.scripts.qa.all
import modelscript.scripts.qc.all
import modelscript.scripts.relations.all
import modelscript.scripts.scenarios.all
import modelscript.scripts.stories.all
import modelscript.scripts.tasks.all
import modelscript.scripts.textblocks.all
import modelscript.scripts.usecases.all
