# coding=utf-8
import modelscripts.scripts.accesses.all
import modelscripts.scripts.classes.all
import modelscripts.scripts.glossaries.all
import modelscripts.scripts.megamodels.all
import modelscripts.scripts.metamodels.all
import modelscripts.scripts.objects.all
import modelscripts.scripts.story.all
import modelscripts.scripts.permissions.all
import modelscripts.scripts.scenarios.all
import modelscripts.scripts.tasks.all
import modelscripts.scripts.usecases.all