        //@Metric "plain class" 1
        //@Metric "class" 1
        //@Metric "association class" 0
        //@Metric "attribute" 10

class model Cl_class02

class A
    attributes
        a : Integer
        / b : Boolean
        / +c : Integer
        / -d : Integer
        / #e : Integer
        / ~f : Integer
        g : Integer {tag1, tag2}
        h : Integer{tag1, id}
        i : Integer{tag1, readOnly}
        j : Integer{tag1, id, readOnly}