        //@Metric "plain class" 3
        //@Metric "class" 3
        //@Metric "association class" 0
        //@Metric "attribute" 3
        //@Metric "enumeration literal" 2

class model Cl_class01

class A

class B
    attributes

enumeration Jour
    lundi
    mardi

class C
    attributes
        a : Integer
            | Documentation of a
        b : Jour
        c : String
            | Documentation of c