    #@Metric "enumeration" 1
    #@Metric "enumeration literal" 2
    #@Metric "class" 1
    #@Metric "plain class" 1
    #@Metric "association" 0
    #@Metric "plain association" 0
    #@Metric "association class" 0
    #@Metric "attribute" 8

class model Cl_class03

enumeration Jour
    lundi
    mardi

class A
    attributes
        a : Jour
        b : String
        c : Real
        d : Boolean
        e : Integer
        f : Date
        g : DateTime
        h : Time